# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_id', models.IntegerField(default=None)),
                ('C_name', models.CharField(max_length=100)),
                ('C_icon', models.FileField(blank=True, null=True, upload_to='')),
                ('Airtel', models.IntegerField(null=True)),
                ('GTPL', models.IntegerField(null=True)),
                ('TataSky', models.IntegerField(null=True)),
                ('DishTV', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emailid', models.EmailField(blank=True, max_length=100)),
                ('mobileno', models.IntegerField(blank=True, default=None, null=True)),
                ('distributor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_id', models.IntegerField(default=None)),
                ('D_name', models.CharField(max_length=100)),
                ('D_string', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_id', models.IntegerField(default=None)),
                ('S_name', models.CharField(max_length=100)),
                ('S_icon', models.FileField(blank=True, null=True, upload_to='')),
                ('D_name', models.CharField(max_length=100)),
                ('C_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Starting_time', models.TimeField(default=None)),
                ('Ending_Time', models.TimeField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='Friday',
            field=models.ManyToManyField(related_name='friday', to='Remote.Time'),
        ),
        migrations.AddField(
            model_name='show',
            name='Monday',
            field=models.ManyToManyField(related_name='monday', to='Remote.Time'),
        ),
        migrations.AddField(
            model_name='show',
            name='Saturday',
            field=models.ManyToManyField(related_name='saturday', to='Remote.Time'),
        ),
        migrations.AddField(
            model_name='show',
            name='Sunday',
            field=models.ManyToManyField(related_name='sunday', to='Remote.Time'),
        ),
        migrations.AddField(
            model_name='show',
            name='Thursday',
            field=models.ManyToManyField(related_name='thursday', to='Remote.Time'),
        ),
        migrations.AddField(
            model_name='show',
            name='Tuesday',
            field=models.ManyToManyField(related_name='tueday', to='Remote.Time'),
        ),
        migrations.AddField(
            model_name='show',
            name='Wednesday',
            field=models.ManyToManyField(related_name='wednesday', to='Remote.Time'),
        ),
    ]
