# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote', '0003_remove_customer_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobileno',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
